version: "3"

services:
  database:
    image: mysql:5.7
    container_name: mail-mysqldb
    env_file:
      - "./.env"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    
    networks:
      - network-tier
    platform: linux/amd64
  
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: mail-redis
    ports:
      - "6379:6379"

networks:
  network-tier:
    external: true
volumes:
  mysql-data:
